### ISSUE TITLE
Volto bookmarks

### ISSUE THREAD

**Issue by ksuess** [collective/collective.bookmarks#3]
Hi @agitator @jensens @MrTango 
I am interested to offer bookmarking for Volto. This package seems to provide an api. Just to let you know that I am investigating if this can be used to communicate with the backend. 
Kind regards, Katja

**Comment by ksuess** [comment]
I'll use branch https://github.com/collective/collective.bookmarks/commits/mrtango-custom-elements, yes?

**Comment by agitator** [comment]
yes, that branch has the latest changes.
Curious how that could work for volto as well...

**Comment by jensens** [comment]
Why not with Volto! It has a plone.rest based API endpoint ready to use. It may need some polishing. Also I am not sure if the Readme is up to date.

**Comment by ksuess** [comment]
Volto bookmarks via collective.bookmarks API are prereleased
With upcoming Volto 12 and https://github.com/collective/collective.bookmarks/pull/4 approved and merged 
### volto-bookmarks
https://github.com/collective/volto-bookmarks provides a bookmarking feature for Volto: **Bookmarking of content even with params as in search queries**

@agitator @jensens @MrTango
